### ISSUE TITLE
 Cannot find module './build/Release/re2' error on Azure Functions

### ISSUE THREAD

**Issue by RezaRahmati** [uhop/node-re2#104]
Hi

When I try to use the library on Azure Functions I get below error

`Worker was unable to load function HttpTrigger1: 'Error: Cannot find module './build/Release/re2''Stack: Error: Cannot find module './build/Release/re2'at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)at Function.Module._load (internal/modules/cjs/loader.js:562:25)at Module.require (internal/modules/cjs/loader.js:692:17)at require (internal/modules/cjs/helpers.js:25:18)at Object.<anonymous> (C:\home\site\wwwroot\node_modules\re2\re2.js:3:13)at Module._compile (internal/modules/cjs/loader.js:778:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)at Module.load (internal/modules/cjs/loader.js:653:32)at tryModuleLoad (internal/modules/cjs/loader.js:593:12)at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

I downgraded my azure function node from 14 to 10, still same error

**Comment by uhop** [comment]
I don’t have access to nor experience with Azure functions. More information, like a version of npm, an output of a package being built, would help a lot.

**Comment by uhop** [comment]
Closing until we have more activity in this ticket.
