### ISSUE TITLE
Allow manually supplying binary

### ISSUE THREAD

**Issue by cideM** [uhop/node-re2#107]
Please let users use their OS package manager for binary dependencies and let them supply the path to that binary through an env variable so that `node-re2` doesn't try to download and/or compile anything on its own.

**Comment by uhop** [comment]
We already have `RE2_DOWNLOAD_MIRROR` (see [wiki](https://github.com/uhop/node-re2/wiki/Precompiled-versions)). Would it work for you?

If not, could you elaborate on how to use existing binaries? Some code ideas would be helpful.

**Comment by cideM** [comment]
I am using NixOS, an operating system where every build is done in a sandbox that does not allow network access. One option of downloading something is to declare the `sha256` upfront. But this only applies when Nix (the language powering NixOS) is doing the downloading. A random Javascript package that's a transitive dependency of something else won't work. So essentially `postInstall` makes it almost impossible to package these dependencies.

For example `esbuild` has [`ESLINT_BINARY_PATH`](https://github.com/evanw/esbuild/commit/5d7a5031274cbc416d8fb3863b3946670c2ddd20) which essentially replaces the entire `postInstall` script.

**Comment by elazutkin-dynata** [comment]
If a path to binary would work for you, it is not difficult to add. It'll be in the next release.

**Comment by uhop** [comment]
If a path to binary would work for you, it is not difficult to add. It'll be in the next release.

**Comment by cideM** [comment]
That would definitely work, thank you very much for understanding 🚀

**Comment by uhop** [comment]
This (unreleased yet) feature is described in the wiki: https://github.com/uhop/install-artifact-from-github/wiki/Making-local-mirror

**Comment by uhop** [comment]
Released as 1.17.2. For more details see:

* https://github.com/uhop/node-re2/wiki/Precompiled-versions#private-mirrors
* https://github.com/uhop/install-artifact-from-github/wiki/Installing
* https://github.com/uhop/install-artifact-from-github/wiki/Making-local-mirror
