### ISSUE TITLE
re2 package has vulnerability dependencies 

### ISSUE THREAD

**Issue by stasharosh** [uhop/node-re2#113]
Please update **ansi-regex** cause it's already outdated and has vulnerability
![phone_pool_—_-zsh_—_198×54](https://user-images.githubusercontent.com/24318601/138262922-f0c5db77-8c86-4a94-8c39-fb35fa7465d4.png)
t
![phone_pool_—_-zsh_—_198×54](https://user-images.githubusercontent.com/24318601/138262930-a1eac83a-dbb0-49f0-8f56-47f41a78318b.png)
y

**Comment by uhop** [comment]
This is a dependency of node-gyp, which is used to compile the source, not to process a user input. re2 doesn’t call ansi-regex anywhere.

**Comment by uhop** [comment]
The deps are updated and the warning has gone. It will be published with 1.17.0.
