### ISSUE TITLE
String replace using RE2 for end of line "$" with "g" flag behaves incorrectly

### ISSUE THREAD

**Issue by CagdasBayram-at** [uhop/node-re2#123]
`"foo".replace(new RE2("$", "g"), "END")` yields `ENDfENDoENDoEND`
The expectation per [RE2](https://github.com/google/re2) is `fooEND`

**Comment by uhop** [comment]
It looks like a problem with the underlying library. I will investigate more.

**Comment by uhop** [comment]
Nope, it is my bug.

**Comment by CagdasBayram-at** [comment]
Thank you Eugene!

**Comment by uhop** [comment]
Published as 1.17.3.
