### ISSUE TITLE
 cannot find module /build/Release/re2 in Azure deploy

### ISSUE THREAD

**Issue by katrina-jh** [uhop/node-re2#132]
My app runs fine locally, but when deployed in Azure, there is the below Application Error. The App was working fine until a few days ago. Do you know what the issue might be, do I have mismatched versions

` cannot find module ‘./build/Release/re2’ ` 

```
node@ 14.15.1
re2@1.16.0
@metascraper/helpers@5.21.10
```

![Screen Shot 2022-08-23 at 12 34 59 pm](https://user-images.githubusercontent.com/83936051/186072514-2164e7b3-15e4-4210-95bc-9ef6a6453e29.png)

**Comment by uhop** [comment]
‘./build/Release/re2’ is being built or copied from the repository when being installed. The latter (copying) is used as an optional speed up. Make sure that your system has all necessary system packages installed as outlined in the `node-gyp` documentation: https://github.com/nodejs/node-gyp

It was reported that in some cases `yarn` or `pnpm` managers can skip the build step completely. In this case try `npm` to see if the problem persists.
