### ISSUE TITLE
Node.js 19 pre-compiled binaries

### ISSUE THREAD

**Issue by JamieMagee** [uhop/node-re2#139]
Node.js 19 was recently released on 18th October. Is it possible to add it to the support matrix and create pre-compiled binaries?

The current list of supported Node.js versions is 14, 16, 18, and 19[^1]

[^1]: https://endoflife.date/nodejs

**Comment by uhop** [comment]
Fixed. Should be out with the next release.

**Comment by uhop** [comment]
Published as [1.17.8](https://www.npmjs.com/package/re2/v/1.17.8).
