### ISSUE TITLE
Breaking Bug: v1.17.8 is broken in worker threads (pointer being freed was not allocated)

### ISSUE THREAD

**Issue by titanism** [uhop/node-re2#143]
This patch version released has broken our builds.  Specifically we're using `ava` (which uses worker threads under the hood).  When we set `workerThreads: false` it works fine, however when we use ava normal default behavior we get a pointer error (see below).

Reference: https://github.com/avajs/ava/issues/3145

```sh
node(1813,0x17272f000) malloc: *** error for object 0x6000010b83a0: pointer being freed was not allocated
node(1813,0x17272f000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    1812 abort      npx ava --serial --fail-fast --verbose
```

Downgrading to v1.17.7 fixes the issue.

Might have stemmed from one of these commits?

- https://github.com/uhop/node-re2/commit/1d17f2b1f012887f95646d4d1b05e2a3b87d49d9
- https://github.com/uhop/node-re2/commit/be7d12d827e0b95942cffc1bb33cfa234e11b8cf
- https://github.com/uhop/node-re2/commit/d719e1df70674ad7e10b3ab3438a793500ec8eda

Ping @uhop 

Thanks as always 🙏

**Comment by uhop** [comment]
`1.17.7` has no code changes. But the following related dependencies were updated:
* `node-gyp` &mdash; used as a build system and as a Node-specific library.
* `nan` &mdash; a Node-specific library.
* C++ version was bumped to C++20.

Either the dependencies introduced a bug or a new toolchain exposed a latent bug in my/`re2` code. :-(

**Comment by uhop** [comment]
@titanism could you create a minimal repro case? It’ll help to debug the problem.

**Comment by uhop** [comment]
@titanism another important question: what platform did fail? Just Windows? Anything else?

**Comment by uhop** [comment]
>That being said, the project is fully open source on GitHub, and you can easily reproduce it as follows

Let me guess: it requires multiple servers to configure and run and contains mounds of non-trivial code. ;-)

Before I started to dig inside: is it possible that you to allocate an RE2 object in one thread and free it in the other?

Hmm, doing so should be valid. Allocating/freeing across process boundaries is not valid. Unless you run different V8 engines per thread.

**Comment by uhop** [comment]
I probably should post the comment here instead of the closed issue. Anyway this is the link: https://github.com/uhop/node-re2/issues/73#issuecomment-1781984355
