### ISSUE TITLE
re2 capture group index start/end location of matches

### ISSUE THREAD

**Issue by teebu** [uhop/node-re2#152]
I'm trying to get index start/stop locations of group matches using RE2. I noticed it works fine in JAVA implementation of RE2. However im running into difficulties getting similar functionality with node. 

I realize the `d` flag is specific to javascript. 

```
var RE2 = require("re2");

// with default flags
let re = new RE2(/a (bc) (de)/d);
let result = re.exec("a bc de");
console.log(result)

result = /a (bc) (de)/d.exec("a bc de");
console.log(result)
```

results from re2 and built in:
```
[
  'a bc de',
  'bc',
  'de',
  index: 0,
  input: 'a bc de',
  groups: undefined
]

[
  'a bc de',
  'bc',
  'de',
  index: 0,
  input: 'a bc de',
  groups: undefined,
  indices: [ [ 0, 7 ], [ 2, 4 ], [ 5, 7 ], groups: undefined ]
]
```

**Comment by uhop** [comment]
“d” flag is new and not implemented (yet?).

**Comment by teebu** [comment]
It is fairly new. Thanks for the quick response. Is there any plans on adding it?

**Comment by uhop** [comment]
There were no plans to implement it. :-) Now I think we should. I don't know when I can allocate time to do it, but PRs will be considered.

**Comment by teebu** [comment]
Thanks @uhop
