### ISSUE TITLE
Git submodules make it difficult to use patched versions of the package.

### ISSUE THREAD

**Issue by cakoose** [uhop/node-re2#16]
I needed to make a small patch to node-re2 to get it to install on macOS.  My normal procedure is to submit the fix upstream, but also point my "package.json" at a temporary fork so our team can continue working right:

```
    "re2": "git+ssh://git@github.com/cakoose/node-re2#...",
```

While this works for most packages, this doesn't work for this package.  On `npm install`:

```
> node-gyp rebuild

  CXX(target) Release/obj.target/re2/lib/addon.o
In file included from ../lib/addon.cc:1:
../lib/./wrapped_re2.h:8:10: fatal error: 're2/re2.h' file not found
#include <re2/re2.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/re2/lib/addon.o] Error 1
```

I eventually figured out that when NPM installs from a "git+ssh" source, it doesn't automatically import all submodules.

My workaround was to `npm publish` a scoped package to NPM (`@cakoose/re2`) and install that.  That required a few additional steps, which made it a little more annoying.  (Though the most annoying thing was how long it took me to figure out that submodules were the issue.)

I'm not sure the best way forward, I just wanted to bring this issue to your attention.  `git subtree` is an alternative that just copies the remote code into your repo, which is maybe not as elegant, but does eliminate some of the submodule headaches.  Or maybe this is not that big a deal :-)

(I do like the idea of Git submodules, but they seem to suffer from poor support in various tools.  Even Git itself doesn't support them well; submodules should really be handled automatically by `clone` and `checkout`.  There was someone working on improving submodules, but I haven't seen any updates in a while: https://github.com/jlehmann/git-submod-enhancements/wiki)

**Comment by uhop** [comment]
I have no clear idea on how to organize it better myself. :-(

Originally I included the RE2 source code as a copy. The decision was simple as I had no choice: the original codebase was not updated, its hosting was going out, I found no alive copies of the RE2 repository.

Then the project started to gain some use (with 0 advertisement, not a single blog post), and users started to complain that they want live updates. At that time I found that some people reanimated the RE2 project on github, fixed some bugs, and landed minor enhancements. So I accepted a pull request for submodules: 1187d8d7fb94443f7c83e344ced12098c2a1a6a8.

In general it is always a problem with native dependencies &mdash; there is no good packaging for C++ libraries, so git it is, and the only tool git has is submodules. I briefly entertained downloading RE2 tarballs directly from github as an installation step. While it is possible, it requires some shell-file-level tooling, which makes it even more OS-dependent.

You can read the discussion in relevant pull requests: #6, #7.

**Comment by uhop** [comment]
I am closing this issue until there is a clear alternative to what we have now. Pull requests are welcome!
