### ISSUE TITLE
Node.js 20 precompiled binaries

### ISSUE THREAD

**Issue by JamieMagee** [uhop/node-re2#165]
Node.js v20 was released last week[^1]. Is it possible to provider precompiled binaries for it?

If it helps, you should be able to stop building precompiled binaries for Node.js v14, as support for it ends on the 30th April[^2]

[^1]: https://nodejs.org/en/blog/release/v20.0.0
[^2]: https://github.com/nodejs/release#release-schedule

**Comment by uhop** [comment]
Released in https://github.com/uhop/node-re2/releases/tag/1.18.1
