### ISSUE TITLE
Bug in var RE2 = require("re2");

### ISSUE THREAD

**Issue by adityagamer786** [uhop/node-re2#189]
I am using react. When I do, `var RE2 = require("re2");`.
I get

> Uncaught TypeError: Cannot set properties of undefined (setting 'Symbol(Symbol.match)')
>     at ./node_modules/re2/re2.js (re2.js:6:1)
>     at options.factory (react refresh:6:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at fn (hot module replacement:62:1)
>     at ./src/pages/OnboardingPage.js (OnboardingPage.js:20:1)
>     at options.factory (react refresh:6:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at fn (hot module replacement:62:1)
>     at ./src/App.js (check_success.svg:29:1)
>     at options.factory (react refresh:6:1)

OnboardingPage.js:20 
`var RE2 = require("re2");`
./node_modules/re2/re2.js :

```
if (typeof Symbol != 'undefined') {
  Symbol.match &&
    (RE2.prototype[Symbol.match] = function (str) {
      return this.match(str);
    });
```

Symbol.match is on line 6

**Comment by uhop** [comment]
This project is for Node only. It will not work on a browser. Sorry.

**Comment by adityagamer786** [comment]
I get same error in node too. I have added it index.js, but still I am having same error

**Comment by uhop** [comment]
How to repro? It'll help to have a minimal `package.json`, a test file, and a sequence of commands that demonstrate the problem. Thank you in advance.

**Comment by uhop** [comment]
Closing in favor of https://github.com/uhop/node-re2/issues/190
