### ISSUE TITLE
Getting RE2.prototype.source crashes Node

### ISSUE THREAD

**Issue by Exter-N** [uhop/node-re2#19]
While `RegExp.prototype.source` returns `'(?:)'` on my machine (with Node v8.2.1), `RE2.prototype.source` crashes Node completely with the following C++ exception :
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abandon (core dumped)
```

It looks like `Nan::ObjectWrap::Unwrap<WrappedRE2>(info.This())` returns a corrupt `WrappedRE2*` when `this === RE2.prototype`, here : https://github.com/uhop/node-re2/blob/e7702c0fe1d374c707152b0a02f80886bedfcbea/lib/accessors.cc#L7-L10

This problem also impacts all of the `RE2.prototype` properties, although in a less severe way, for example `true === RE2.prototype.global`, `true === RE2.prototype.ignoreCase`, `true === RE2.prototype.multiline` on my machine while the same properties of `RegExp.prototype` are all equal to `undefined`.

**Comment by uhop** [comment]
Fixed in #20.
