### ISSUE TITLE
RE2 objects silently work like /u RegExp objects

### ISSUE THREAD

**Issue by Exter-N** [uhop/node-re2#21]
Since ES2015 there is a `u` flag which changes the way the `RegExp` engine processes Unicode surrogates and characters from supplementary planes (see [ECMAScript® 2015 Language Specification – Text Processing – RegExp (Regular Expression) Objects – Pattern Semantics](https://www.ecma-international.org/ecma-262/6.0/#sec-pattern-semantics)).

For example, without this flag :
```js
let charRE = /./g;
charRE.exec("😃")[0] === "\uD83D";
charRE.exec("😃")[0] === "\uDE03";
charRE.exec("😃") === null;
let emojiRE = /[😃-😅]/; // SyntaxError, this gets parsed as a character class containing \uD83D, the range from \uDE03 to \uD83D (which is lower, hence the SyntaxError), and \uDE05
```

With this flag :
```js
let charRE = /./gu;
charRE.exec("😃")[0] === "😃";
charRE.exec("😃") === null;
let emojiRE = /[😃-😅]/u; // OK, this gets parsed as a character class containing the range from \u{1F603} (😃) to \u{1F605} (😅)
```

(I took emoji as an example because that's probably the most popular use of characters from supplementary planes, but there are many more usages of the feature, see [Wikipedia – Plane (Unicode)](https://en.wikipedia.org/wiki/Plane_(Unicode)))

The `RE2` engine always has the second behavior, but the wrapper class provided by this module silently ignores the `u` flag in its constructor, doesn't have an `unicode` property (which is the `RegExp` property associated to this flag), and doesn't give back the flag when `.toString()` is called on it.

For the property there would be a simple solution (create it and make it always return `true`), but modifying the constructor and `.toString()` would cause many problems, ranging from consistency to backward compatibility breaks :
- The constructor could either continue silently ignoring it (inconsistency with the property and the behavior) or require it and throw if it is not present (obvious BC break) ;
- `.toString()` could either continue not returning it (inconsistency with the property and the behavior) or silently add it (potential BC break for any code that consumes the returned string) … or it could add it if and only if it was passed to the constructor (still a partial inconsistency) ;
- The property could also be made to return whether the flag was passed to the constructor but it would increase the inconsistency, as the behavior is to always work as if it was passed.

The problem with the BC breaks are that fixing this is probably not a big enough addition to justify bumping the major version, but breaking BC would require it if you follow SemVer.

**Comment by uhop** [comment]
`RE2` supports only "traditional" features, and do not support anything introduced in ES2015 and later (like sticky bits). Partially it is because the underlying engine does not support some features. Having said that I am open to adding more functionality, if it makes sense, and can be done in a reasonable way.

**Comment by Exter-N** [comment]
The tests I ran show that the engine only works in the new mode and doesn't support the "traditional" one. The problem here is that the library reports that it works in the "traditional" mode and that can't be fully fixed without several BC breaks. (that's why I didn't open a PR for this one, I'm not sure about which kind of change you prefer for each of the impacted functions)

**Comment by uhop** [comment]
I tested RE2 with your examples, and it does appear that it always works in the Unicode mode. I find it strange, because, as you probably aware, `node-re2` has no code that interprets USC-2 as UTF-16 by parsing code points as surrogate pairs &mdash; it is all done in `String` implementation of `Nan` and ultimately `V8`. Specifically, it appears to be done in `WriteUtf8()` and `Utf8Length()` methods, both of which are outside of our control in the V8 engine. As a matter of fact, I don't know how to turn such parsing off or affect it in any other way.

We need to do more research. One possibility is to implement such conversion in `node-re2` by copying 16-bit characters to a local buffer, then manually converting it to UTF-8 ignoring purposely surrogate pairs (if it even makes sense). I don't like this solution, because it probably will be slower than what we have now due to the extra copying. Oh, well.

**Comment by Exter-N** [comment]
IMHO, manually converting to UTF-8 ignoring surrogate pairs indeed doesn't make much sense unless someone has an actual use case for that, and is a quite ugly hack.

Therefore I would recommend to not implement that into `node-re2` until it's actually needed by someone, and for now, just make it report that it works in Unicode mode as I proposed in the original post of the issue.

In a 1.7.* or 1.8+ release it could :
- Add a `.unicode` property, always retuning `true` ;
- Maybe add the `u` character to the `.flags` property ;
- Maybe add the `u` character to the `.toString()` return value ;
- Maybe emit a deprecation warning the 1st time the `RE2` constructor is called without the `u` character in the `flags` argument (with `console.error` ? something like Node running the equivalent of `console.error("(node:" + process.pid + ") [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.");` the 1st time it sees an unhandled rejected `Promise`).

In a 2.0 release it could :
- Add the `u` character to the `.flags` property if not already done ;
- Add the `u` character to the `.toString()` return value if not already done ;
- Throw an exception when the `RE2` constructor is called without the `u` character in the `flags` argument.

In a 2.1+ or 3+ release it could then implement the conversion if someone has an actual need for it.

**Comment by uhop** [comment]
Thanks for your thoughts. I appreciate it. Most of them make sense to me, but throwing an exception seems too harsh, especially given into account the original goal to be as drop-in compatible as possible. :-)

Personally, I don't see much sense in using regular expressions without the Unicode mode. I suspect it was done mostly for back-compat reasons. I am willing to do it for the same compatibility reasons with the current `RegExp` implementation &mdash; it is harder to explain differences than to be compatible.

**Comment by uhop** [comment]
The commit a475294b6ac68e00aa358124d61269a6ca4313cc closes this issue.
