### ISSUE TITLE
Add .flags property

### ISSUE THREAD

**Issue by Exter-N** [uhop/node-re2#22]
The `RegExp` class supports a `flags` property which returns the flags passed to the constructor, in a canonicalized order (see [ECMAScript® 2015 Language Specification – Text Processing – RegExp (Regular Expression) Objects – Properties of the RegExp Prototype Object – get RegExp.prototype.flags](https://www.ecma-international.org/ecma-262/6.0/#sec-get-regexp.prototype.flags)).

The `RE2` class doesn't support this property.

As for #21, if this property gets implemented, should it always include the `u` flag ? Only include it if it was passed to the constructor ? Or never include it ? (it would not pose BC problems as the property currently doesn't exist, as opposed to adding it to `.toString()`)

**Comment by uhop** [comment]
I separated the implementation of the unicode flag into #35.

**Comment by uhop** [comment]
See #21.
