### ISSUE TITLE
No support for the /y (sticky) RegExp flag

### ISSUE THREAD

**Issue by Exter-N** [uhop/node-re2#23]
ES2015 added a `y` (`sticky`) flag to the `RegExp` class, which has a behavior similar to the `g` flag, but instead of looking for a match starting from `.lastIndex`, it looks for a match exactly *at* `.lastIndex`, and other small differences (see [ECMAScript® 2015 Language Specification – Text Processing – RegExp (Regular Expression) Objects – Properties of the RegExp Prototype Object – RegExp.prototype.exec ( string ) – Runtime Semantics: RegExpExec ( R, S )](https://www.ecma-international.org/ecma-262/6.0/#sec-regexpbuiltinexec)).

For example, this flag is extremely useful as an optimization for writing parsers.

The `RE2` class doesn't support this flag.

**Comment by uhop** [comment]
Actually, I needed a sticky bit for one of my projects and looked into that. At the moment the underlying engine (`RE2` written in C++) had no such support, and was, more or less, an abandonware. I am not sure the current state supports it.

**Comment by Exter-N** [comment]
This one should be fixed by #33.
