### ISSUE TITLE
.source and .toString() don't do the proper escaping

### ISSUE THREAD

**Issue by Exter-N** [uhop/node-re2#24]
The `RegExp` `.source` property and `.toString()` method escape the pattern in such a way that `new RegExp(re.source, re.flags)`, `eval('/' + re.source + '/' + re.flags)` and `eval(re.toString())` are all valid, and all give a `RegExp` with the same characteristics as `re` (see [ECMAScript® 2015 Language Specification – Text Processing – RegExp (Regular Expression) Objects – The RegExp Constructor – Abstract Operations for the RegExp Constructor – Runtime Semantics: EscapeRegExpPattern ( P, F )](https://www.ecma-international.org/ecma-262/6.0/#sec-escaperegexppattern)).

The `RE2` class doesn't do this, for example :
```js
let re2 = new RE2('foo/bar', '');
re2.toString(); // '/foo/bar/'
let re = eval(re2.toString()); // SyntaxError: Invalid regular expression flags
```

**Comment by uhop** [comment]
It appears to be fixed.
