### ISSUE TITLE
Add named groups

### ISSUE THREAD

**Issue by uhop** [uhop/node-re2#34]
Last versions of Node support named groups described in http://2ality.com/2017/05/regexp-named-capture-groups.html

**Comment by Exter-N** [comment]
It looks like the RE2 API for this is not too complicated. I'll probably try to create a PR for this but I have to look at the ES2018 spec before.

**Comment by uhop** [comment]
Thanks for the PR. I'll add tests, and update docs preparing for the next release.

**Comment by uhop** [comment]
Done in previous commits.
