### ISSUE TITLE
unrecognized command line option in install

### ISSUE THREAD

**Issue by rubenbarreiro** [uhop/node-re2#45]
Hello there.

i'm trying to install the module without any special setup, `npm i --save re2` but I got this error related to gcc.  

```

> re2@1.8.2 install /home/mypc/Desktop/node_modules/re2
> node-gyp rebuild

make: Entering directory '/home/mypc/Desktop/node_modules/re2/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
g++: error: unrecognized command line option ‘-Wimplicit-fallthrough=0’
re2.target.mk:153: recipe for target 'Release/obj.target/re2/lib/addon.o' failed
make: *** [Release/obj.target/re2/lib/addon.o] Error 1
make: Leaving directory '/home/mypc/Desktop/node_modules/re2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mypc/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-24-generic
gyp ERR! command "/home/mypc/.nvm/versions/node/v8.9.0/bin/node" "/home/mypc/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mypc/Desktop/node_modules/re2
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN desktop@1.0.0 No description
npm WARN desktop@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! re2@1.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the re2@1.8.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mypc/.npm/_logs/2018-07-11T22_53_01_875Z-debug.log
```

Maybe someone stumbled upon this in the past. I don't know if i'm ignoring some required lib.

More info about my system 
```
OS: Ubuntu 16.04.4
Nodejs: v8.9.0
npm: 5.5.1
gcc: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

best regards

**Comment by uhop** [comment]
The real problem is that every single version of gcc adds more and more warnings, which obscure everything else. I started to suppress warnings that come from a code I do not control &mdash; `Nan` and the `re2` core respectively. Unfortunately, older versions do not understand names of some warnings they do not support and instead of ignoring them a compilation fails. This situation is untenable.

Apparently starting with gcc 4.4 an option was added to treat such "errors" as warnings specifically to combat the problem. I'll try to play with it to see how it works in practice. Get ready to try the fix out in a day or two.

**Comment by uhop** [comment]
Could you try now? Clone the repo locally, and run `npm i` in its directory.

**Comment by rubenbarreiro** [comment]
righty. my main os(ubuntu) and gcc `5.4` now throws this 

```
> re2@1.8.2 install /home/mypc/Desktop/re22
> node-gyp rebuild

make: Entering directory '/home/mypc/Desktop/re22/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
  CXX(target) Release/obj.target/re2/lib/new.o
  CXX(target) Release/obj.target/re2/lib/console.o
  CXX(target) Release/obj.target/re2/lib/exec.o
  CXX(target) Release/obj.target/re2/lib/test.o
  CXX(target) Release/obj.target/re2/lib/match.o
  CXX(target) Release/obj.target/re2/lib/replace.o
  CXX(target) Release/obj.target/re2/lib/search.o
  CXX(target) Release/obj.target/re2/lib/split.o
  CXX(target) Release/obj.target/re2/lib/to_string.o
  CXX(target) Release/obj.target/re2/lib/accessors.o
  CXX(target) Release/obj.target/re2/lib/util.o
make: *** No rule to make target 'Release/obj.target/re2/vendor/re2/bitstate.o', needed by 'Release/obj.target/re2.node'.  Stop.
make: Leaving directory '/home/mypc/Desktop/re22/build'
```

but alpine with gcc `6.3` seems to be just fine, just a warning
```
npm WARN lifecycle re2@1.8.2~install: cannot run in wd %s %s (wd=%s) re2@1.8.2 node-gyp rebuild /root/node-re2
added 4 packages in 0.382s
```

**Comment by rubenbarreiro** [comment]
Sorry. I closed this by accident

**Comment by uhop** [comment]
> righty. my main os(ubuntu) and gcc 5.4 now throws this

Interesting. It works on [Travis-CI](https://travis-ci.org/uhop/node-re2/jobs/403322651) with gcc 4.8:

```
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Obviously now it spams about some attributes it doesn't understand.

It appears that [gcc 4.8.1 is a minimal version](https://gcc.gnu.org/projects/cxx-status.html#cxx11), because: ["Your compiler must support C++11. In particular, the DFA execution engine depends on C++11 atomics."](https://github.com/google/re2/wiki/Install) Incidentally this is the version used by [Nan on Travis-CI](https://github.com/nodejs/nan/blob/master/.travis.yml).

With gcc 5.4 it throws because of some make rules (?) for a file from another project, both of which I do not control, e.g., `Makefile` is generated by `node-gyp`.

`node-gyp` depends on Python 2.x (even 2.7.x specifically), `make` and `gcc`, but I cannot find the exact requirements for Linux or Mac.

To be frank I am at loss.

**Comment by uhop** [comment]
Just tried on Travis-CI with gcc 5 (I think 5.5), and it runs without problems.

**Comment by rubenbarreiro** [comment]
gotcha. will try that version in ubuntu

**Comment by rubenbarreiro** [comment]
well, could not test with that version easily. Installation was a little tricky, so I used `6.4` that worked. So, possibly `gcc >= 5.5` should be the minimal working version, at least in `ubuntu 16.04`?. For `ubuntu 14.04` as you tested in travis is `gcc 4.8`

**Comment by uhop** [comment]
Could you file this problem with [node-gyp](https://github.com/nodejs/node-gyp)? Unfortunately, I do not have all the information they need, and I cannot repro with available platforms.

Some background: `gyp` does not even provide tools to target different compiler versions, only processor architectures, and operating system types. It appears that the preferred way for dependent projects is to define what gcc versions required to compile (like in `node=re2`'s `.travis.yml`), which is clearly a burden in some cases. It looks like in your case `Makefile` is not generated properly, which is clearly a `gyp` problem.

I'll put an advice in README to use compiler >= 5.5.

**Comment by rubenbarreiro** [comment]
Ok, will create an issue over there :+1: 

Thx you very much for your help.

**Comment by gabegorelick** [comment]
@uhop Is this fixed on `master` since `-Wimplicit-fallthrough=0` is no longer in `cflags`? If so, do you mind cutting a new release?

**Comment by uhop** [comment]
Will do.

**Comment by pjtatlow** [comment]
So will the next release remove `-Wimplicit-fallthrough=0` from the flags? If so, when is the next release planned?

**Comment by uhop** [comment]
The next release is planned for the upcoming weekend.

**Comment by uhop** [comment]
Done: 1.8.3.
