### ISSUE TITLE
Console flooded with -Wcast-function-type 

### ISSUE THREAD

**Issue by JamieMagee** [uhop/node-re2#50]
Building `node-re2` locally my console is flooded with `-Wcast-function-type` warnings. I compared to building re2 from source, which is much more silent. You can see the output [here](https://gist.github.com/JamieMagee/71899f12395d0965e3b45cb61dd90a3d).

It looks like they've fixed these warnings upstream. Is it possible to update from upstream and cut a release?

My local environment is:
node 12.9.1
node-gyp 5.0.2
GCC 9.1.0

**Comment by uhop** [comment]
Cool. I'll try to cut it this weekend.

**Comment by uhop** [comment]
Thanks.

**Comment by uhop** [comment]
I published [1.10.1](https://github.com/uhop/node-re2/tree/1.10.1) with your changes (thanks again!). It still floods the console with warnings from `v8.h` and `nan.h`. I looked at it and I don't think it is something I can do without modifying those sources. :-(

**Comment by JamieMagee** [comment]
Thanks for merging the PR.

Yeah, I'm also seeing the same issues. I assumed it was due to the outdated version of `re2`, but maybe the Makefile in `re2` is hiding the output, but `node-gyp` is printing it to the terminal? I'm unsure, but it looks like these warnings should be fixed upstream.
