### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by JamieMagee** [uhop/node-re2#52]
Is it possible to add typescript types? I've added them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3cf733f73a7e2c345081793a0958cbcb1f662294), and they're published under `@types/re2`, but it would be much easier to incorporate them into re2 directly.

**Comment by uhop** [comment]
Sure thing but I need your help. Please make a PR and I'll merge it.
