### ISSUE TITLE
Implicit dependency on node-gyp

### ISSUE THREAD

**Issue by JamieMagee** [uhop/node-re2#62]
Using Yarn 2, I get the following warning:

```
re2@npm:1.10.5: Implicit dependencies on node-gyp are discouraged
```

[Yarn's advice](https://yarnpkg.com/advanced/error-codes#yn0032---node_gyp_injected) is to add an explicit dependency on `node-gyp`

**Comment by uhop** [comment]
Added in https://github.com/uhop/node-re2/commits/1.11.0
