### ISSUE TITLE
Can't import/require

### ISSUE THREAD

**Issue by ChunxiAlexLuo** [uhop/node-re2#63]
```
ERROR in ./node_modules/re2/build/Release/re2.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
```

Tried to open re2.node then get

`the file is not displayed in the editor because it is either binary or uses unsupported`

I want to use it with webpack

**Comment by uhop** [comment]
Two questions:

1. Could you provide a minimal repro case?
2. This is a Node-only binary extension. Why exactly do you need a webpack for? I am asking because usually it is used to process assets for web browsers.

**Comment by ChunxiAlexLuo** [comment]
> Two questions:
> 
> 1. Could you provide a minimal repro case?
> 2. This is a Node-only binary extension. Why exactly do you need a web pack for? I am asking because usually it is used to process assets for web browsers.

I have a front-end project contained lots of regex which might have ReDoS risks, I wonder if RE2 could be used in react project, or node.js only

**Comment by ChunxiAlexLuo** [comment]
Or for the client-side, ReDoS risks doesn't matter at all, as long as these regexes won't be passed to the server-side, because people will not attack their self web browser, sorry for my naive question

**Comment by uhop** [comment]
This project is for Node only. It will not work on a browser. Sorry.

**Comment by burdell** [comment]
I use Webpack to bundle AWS Lambda functions running on Node and was having problems with. You can use raw-loader to get the file into the bundle:
```
{
    test: /re2\.node$/i,
    use: 'raw-loader'
}
```

**Comment by blueleader07** [comment]
I came across this and raw-loader didn't work for me.  node-loader did work though:
`
{
    test: /\.node$/,
    loader: 'node-loader'
}
`
