### ISSUE TITLE
Error: Cannot find module './build/Release/re2.node'

### ISSUE THREAD

**Issue by allenGKC** [uhop/node-re2#64]
When I install this package and run, it occurs the error"Error: Cannot find module './build/Release/re2.node'"

I have checked the folder and cannot find the build folder?

Does anyone know why?
![image](https://user-images.githubusercontent.com/6214258/80576317-91130a80-8a37-11ea-8fec-1c10afc93c38.png)

**Comment by uhop** [comment]
I just tried on Mac, and it WFM:

```bash
$ npm i re2 --save

> re2@1.11.0 install /Users/eugene.lazutkin/Work/re2-test/node_modules/re2
> node-gyp rebuild

  CXX(target) Release/obj.target/re2/lib/addon.o
  CXX(target) Release/obj.target/re2/lib/new.o
  CXX(target) Release/obj.target/re2/lib/exec.o
  CXX(target) Release/obj.target/re2/lib/test.o
  CXX(target) Release/obj.target/re2/lib/match.o
  CXX(target) Release/obj.target/re2/lib/replace.o
  CXX(target) Release/obj.target/re2/lib/search.o
  CXX(target) Release/obj.target/re2/lib/split.o
  CXX(target) Release/obj.target/re2/lib/to_string.o
  CXX(target) Release/obj.target/re2/lib/accessors.o
  CXX(target) Release/obj.target/re2/lib/util.o
  CXX(target) Release/obj.target/re2/vendor/re2/bitstate.o
  CXX(target) Release/obj.target/re2/vendor/re2/compile.o
  CXX(target) Release/obj.target/re2/vendor/re2/dfa.o
  CXX(target) Release/obj.target/re2/vendor/re2/filtered_re2.o
  CXX(target) Release/obj.target/re2/vendor/re2/mimics_pcre.o
  CXX(target) Release/obj.target/re2/vendor/re2/nfa.o
  CXX(target) Release/obj.target/re2/vendor/re2/onepass.o
  CXX(target) Release/obj.target/re2/vendor/re2/parse.o
  CXX(target) Release/obj.target/re2/vendor/re2/perl_groups.o
  CXX(target) Release/obj.target/re2/vendor/re2/prefilter.o
  CXX(target) Release/obj.target/re2/vendor/re2/prefilter_tree.o
  CXX(target) Release/obj.target/re2/vendor/re2/prog.o
  CXX(target) Release/obj.target/re2/vendor/re2/re2.o
  CXX(target) Release/obj.target/re2/vendor/re2/regexp.o
  CXX(target) Release/obj.target/re2/vendor/re2/set.o
  CXX(target) Release/obj.target/re2/vendor/re2/simplify.o
  CXX(target) Release/obj.target/re2/vendor/re2/stringpiece.o
  CXX(target) Release/obj.target/re2/vendor/re2/tostring.o
  CXX(target) Release/obj.target/re2/vendor/re2/unicode_casefold.o
  CXX(target) Release/obj.target/re2/vendor/re2/unicode_groups.o
  CXX(target) Release/obj.target/re2/vendor/util/pcre.o
  CXX(target) Release/obj.target/re2/vendor/util/rune.o
  CXX(target) Release/obj.target/re2/vendor/util/strutil.o
  SOLINK_MODULE(target) Release/re2.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN re2-test@1.0.0 No description
npm WARN re2-test@1.0.0 No repository field.

+ re2@1.11.0
added 2 packages from 9 contributors and audited 2 packages in 33.238s
found 0 vulnerabilities

$ cat index.js
const RE2 = require('re2');
const pattern = new RE2('1');
console.log(pattern.test('abc'), pattern.test('123'), pattern.test('ab1'));
$ node index.js
false true true
$
```

What exactly do you use and what exactly do you see?

Like almost all Node extensions `re2` uses [node-gyp](https://github.com/nodejs/node-gyp) &mdash; see its requirements in its documentation. Are you able to install and use any other Node extensions?

**Comment by allenGKC** [comment]
@uhop I create a demo and I just install re2 as you said
![image](https://user-images.githubusercontent.com/6214258/80684115-c67f2d00-8af7-11ea-9711-632d2a18ba1a.png)
I look into my node_modules, I can not find the folder named build, I create an index.js file:
![image](https://user-images.githubusercontent.com/6214258/80684304-09410500-8af8-11ea-9faf-f1656f691867.png)
and run, the result shows:
![image](https://user-images.githubusercontent.com/6214258/80684324-152cc700-8af8-11ea-956a-b8229199372b.png)
Should I install any other dependency?

**Comment by elazutkin-dynata** [comment]
What OS do you use? Did you follow the setup process outlined above for `node-gyp` for your OS? You should do it once before using any Node extensions, then it is usually good for all.

I myself develop on Linux (Ubuntu) and I can test on the latest MacOS. Both WFM.

**Comment by uhop** [comment]
What OS do you use? Did you follow the setup process outlined above for `node-gyp` for your OS? You should do it once before using any Node extensions, then it is usually good for all.

I myself develop on Linux (Ubuntu) and I can test on the latest MacOS. Both WFM.

**Comment by allenGKC** [comment]
No more needs for this package but still thanks for your help @uhop
