### ISSUE TITLE
TypeError on Symbol.match when using on ReactJS

### ISSUE THREAD

**Issue by GabrielF9** [uhop/node-re2#67]
Hey, I don't know why but when I'm using the RE2 in ReactJS I receive this error when I import the library:

`TypeError: Cannot set property 'Symbol(Symbol.match)' of undefined`

Using in a clear node project, it works fine, but in React, I only import, save, run and get the error.

Another thing that happens is the replace.cc what get this warning when install in both cases:

```
C:\projetos\regex-safe>npm install --save re2

> re2@1.11.0 install C:\projetos\regex-safe\node_modules\re2
> node-gyp rebuild


C:\projetos\regex-safe\node_modules\re2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Compilando os projetos desta solução um de cada vez. Para habilitar o build paralelo, adicione a opção "/m".
  addon.cc
  new.cc
  exec.cc
  test.cc
  match.cc
  replace.cc
  search.cc
  split.cc
c:\projetos\regex-safe\node_modules\re2\lib\replace.cc(251): warning C4018: '>': incompatibilidade de signed/unsigned [C:\projetos\regex-safe\node_modules\re2\build\re2.
vcxproj]
c:\projetos\regex-safe\node_modules\re2\lib\replace.cc(399): warning C4018: '>': incompatibilidade de signed/unsigned [C:\projetos\regex-safe\node_modules\re2\build\re2.
vcxproj]
  to_string.cc
  accessors.cc
  util.cc
  bitstate.cc
  compile.cc
  dfa.cc
  filtered_re2.cc
  mimics_pcre.cc
  nfa.cc
  onepass.cc
  parse.cc
  perl_groups.cc
  prefilter.cc
  prefilter_tree.cc
  prog.cc
  re2.cc
  regexp.cc
  set.cc
  simplify.cc
  stringpiece.cc
  tostring.cc
  unicode_casefold.cc
  unicode_groups.cc
  pcre.cc
  rune.cc
  strutil.cc
  win_delay_load_hook.cc
     Criando biblioteca C:\projetos\regex-safe\node_modules\re2\build\Release\re2.lib e objeto C:\projetos\regex-safe\node_modules\re2\build\Release\re2.exp
  re2.vcxproj -> C:\projetos\regex-safe\node_modules\re2\build\Release\\re2.node
npm WARN regex-safe@1.0.0 No description
npm WARN regex-safe@1.0.0 No repository field.

+ re2@1.11.0
added 2 packages from 9 contributors and audited 4 packages in 34.136s
found 0 vulnerabilities
```

Any idea what it might be?

**Comment by uhop** [comment]
Are you aware that `node-re2` is a binary extension for Node and cannot be used in browsers?

**Comment by GabrielF9** [comment]
I had imagined it, but I thought it would still work, anyway, thanks for the quick answer!!  Taking advantage of the fact that we are here, would any library know that would do this well for web?

**Comment by uhop** [comment]
Unfortunately, I have no idea. I am not sure we have a valid business case. `RE2` is used mostly for two reasons: speed and to prevent DOS attacks. It is very unlikely anything written in JS can be faster than whatever provided by browser vendors usually written in native code and/or using JIT-compilation for regular expressions. Regarding DOS attacks: it is unlikely a hacker will DOS their own browser/computer. Both these reasons make `RE2` more attractive on a server (with Node) rather than in a browser.

**Comment by GabrielF9** [comment]
Ah yes, that makes sense. It was precisely for this reason (the DOS attack) that I came after RE2. On the website I'm doing, sonarcloud ci indicates several regexes of mine with the ReDos vulnerability. Again, thanks for the help, I will take a closer look at ReDos and see with my boss the best solution. Thanks!
