### ISSUE TITLE
MULTILINE flag fails as separate setting

### ISSUE THREAD

**Issue by frudman** [uhop/node-re2#71]
Not sure why this is not working. This is the test code (after narrowed down the problem):
```
const RE2 = require('re2');
const str = `  line 1
line 2 (at start of line)
  line 3`;

const pat1 = new RE2("^line", "m"); // DOESN'T WORK
const test1 = str.match(pat1);
const pat2 = new RE2("(?m)^line"); // WORKS
const test2 = str.match(pat2);

console.log(test1 ? 'SUCCESS1' : 'FAILS1', test1); // fails
console.log(test2 ? 'SUCCESS2' : 'FAILS2', test2); // succeeds
```

Results:
```
FAILS1 null
SUCCESS2 [
  'line',
  index: 9,
  input: '  line 1\nline 2 (at start of line)\n  line 3',
  groups: undefined
]
```

This is running `node.v14.4.0` on `macOS Catalina (v10.15.4)`.
`process.versions.module === 83` so using [latest version of darwin lib](https://github.com/uhop/node-re2/releases)

Am I doing it wrong? I'm simply trying to match start of lines on multiline strings.

**Comment by uhop** [comment]
Thank you for the repro case.

**Comment by uhop** [comment]
Please try [1.15.0](https://github.com/uhop/node-re2/tree/1.15.0) and let me know if it fixes your problem.
