### ISSUE TITLE
Not able to import re2 in Angular project

### ISSUE THREAD

**Issue by Adityas119** [uhop/node-re2#77]
### Issue

Cannot use `re2` in angular project.

---
### Steps Followed
- Create a new angular project or existing project.
- Install re2 - `npm i re2`
- Import in component or service as - `import 're2';`
---
### Error 
```ERROR in ./node_modules/re2/re2.js
Module not found: Error: Can't resolve './build/Release/re2'```

**Comment by uhop** [comment]
`re2` is a Node binary extension written in C++. As such it cannot be used in browsers directly.
