### ISSUE TITLE
Re2 Requires a lesser NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by samplics** [uhop/node-re2#88]
```
Error: The module '\\?\C:\Users\easto\node_modules\re2\build\Release\re2.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
I have manually deleted and reinstalled re2, as well as rebuilt the module.
This error only happens on windows

**Comment by uhop** [comment]
The release does not include a prebuilt module for ABI 79: https://github.com/uhop/node-re2/releases/tag/1.15.9 &mdash; this is normal and `re2` should be rebuilt automatically.

The policy is to provide builds with the latest `re2` release for the following Node versions:

* All supported LTS releases (as long as security fixes are provided by the maintainers).
* The latest release, if it is not LTS.

At the moment of this writing (11/28/2020), it means versions 10, 12, 14, and 15: https://endoflife.date/nodejs

ABI 79 is Node 13, which is now in the EOL phase. It doesn't mean that `re2` will not work. It just means that the compilation step should be provided by yourself. In practice, it means that the build environment should be set up as outlined in [node-gyp's requirements](https://github.com/nodejs/node-gyp).

I hope it helps. Please let me know if it doesn't answer your question or something went wrong. Just in case this is the list of relevant build-related items from the [wiki](https://github.com/uhop/node-re2/wiki):

* [Precompiled versions](https://github.com/uhop/node-re2/wiki/Precompiled-versions)
* [Problem: ABI mismatch in Electron](https://github.com/uhop/node-re2/wiki/Problem:-ABI-mismatch-in-Electron)
