### ISSUE TITLE
How to detect backreferences?

### ISSUE THREAD

**Issue by davisjam** [uhop/node-re2#9]
I have a small JS script that tries to create an RE2 regex with backreferences. Though it prints errors to stderr, there does not seem to be a way to programmatically determine that the regex contained backreferences.

It looks like the re2.cc code in question sets the RE2's error_ field, so I think exposing the RE2 ok() method would allow the program to realize its mistake.

```
../vendor/re2/re2.cc:194: Error parsing 'android.+(\w+)build\1$': invalid escape sequence: \1
../vendor/re2/re2.cc:579: Invalid RE2: invalid escape sequence: \1
```

**Comment by uhop** [comment]
First of all, backreferences are explicitly not supported: https://github.com/uhop/node-re2#backreferences

Second, for better or for worse the error management is basically Garbage-In-Garbage-Out (GIGO principle).

RE2 tries to simulate RegExp, which doesn't have `ok()`, or any other way to show errors. I suspect that it is meant to throw errors in some situations, wrong escaped symbols is not of them. We can look into throwing errors, but I don't think that a non-standard explicit error check makes sense. What are your thoughts on the matter?

**Comment by davisjam** [comment]
Background: I am programmatically evaluating regular expressions from the wilds of npm, and thus may encounter some with backreferences. It would be nice if I could tell this somehow.

I do realize that backreferences are not supported by RE2. I think, however, that indicating an error in some fashion would be appropriate. `ok` seemed like an option, but you're right that this keeps it from being a nice drop-in for RegExp.

It looks like RegExp will throw errors for invalid regex declarations. Here is an example:

```
> try { var re = /{4}/ } catch (e) { console.log('caught e: ' + e); }
caught e: SyntaxError: Invalid regular expression: /{4}/: Nothing to repeat
```

Throwing a similar error seems like a reasonable way to treat passing backreferences to this module. The same approach would work for #3.

**Comment by uhop** [comment]
Yep, agreed. Now we have to figure out how to throw V8-compatible exceptions from C++, and add appropriate errors.

**Comment by uhop** [comment]
I am not sure RE2 provides extensive checks for validity of regular expressions, and writing the checks myself looks like a daunting task. Any good ideas what to check, and how to check it? I am holding 1.5.0 for that.

PS: Throwing an exception from C++ to JS is a solved task.

**Comment by davisjam** [comment]
This issue is now mostly-solved (the test cases have some TODOs). Let me know your thoughts.

**Comment by uhop** [comment]
Great job on patches and the docs! I guess, I can close it now.

**Comment by davisjam** [comment]
I'm glad to hear you like my work.
