### ISSUE TITLE
A link in the document is outdated

### ISSUE THREAD

**Issue by ocavue** [uhop/node-re2#90]
The [install script] link at https://github.com/uhop/node-re2/blob/a9d912772c47c484083e251847ba48bbea7c84b5/README.md#precompiled-artifacts is outdated and points to a 404 page.

**Comment by ocavue** [comment]
I believe that the link should point to https://github.com/uhop/install-artifact-from-github/blob/master/bin/install-from-cache.js now.

**Comment by uhop** [comment]
Fixed. Will be published with the next release. Thx!
