### ISSUE TITLE
Issue with escaping forward slashes in nodejs

### ISSUE THREAD

**Issue by pal-jjoyce** [uhop/node-re2#95]
When trying to construct RegEx for URLs I have encountered a problem escaping forward slash characters.

The following string is passed to the RE2 constructor to create the regex
```
const regex = new RE2(`^(?i:https?\\:\\/\\/)?(?i:www\\.)?(?i:\\Q${host}\\E)(?:\\Q${path}\\E)$`)
```

If either the host or the path contain a forward slash character it will be double escaped despite being within the \Q \E marks for quoted literals. No other special characters within the \Q \E markers are escaped this way, only the forward slash. This prevents the regex.test function from finding an exact match unless any forward slashes in the string being tested are also double escaped as can be seen in the following example

```
const string = 'te/st';
const regex = new RE2('\\Qte/st\\E');
result = regex.test(string);
console.log(result);

const string = 'te\\/st';
const regex = new RE2('\\Qte/st\\E');
const result = regex.test(entryURL);
console.log(result);
```

The first result will be false while the second result will be true. Is this inteneded behaviour? It seems quite clunky to require forward slashes in strings being matched to be forward escaped prior to testing. Perhaps I am misunderstanding something?

**Comment by uhop** [comment]
`\Q` and `\E` have no special meaning in JavaScript regular expressions. Could you give a reference to a document thta defines them? I would prefer the JavaScript standard or an MDN article. Thank you.

**Comment by uhop** [comment]
I suspect it is not a problem anymore. Please reopen the ticket, if you have new evidence of a non-standard behavior.

**Comment by dt-atkinson** [comment]
These tags are something that isn't JS native but is supported by re2:
https://github.com/google/re2/blob/13ebb377c6ad763ca61d12dd6f88b1126bd0b911/doc/syntax.txt#L114
